global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
  - job_name: "asset-service"
    static_configs:
      - targets: ["asset-service:8001"]
  - job_name: "threat-engine-service"
    static_configs:
      - targets: ["threat-engine-service:8002"]
  - job_name: "ml-service"
    static_configs:
      - targets: ["ml-service:8003"]
